// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Net21_Labb3_API.Data;

#nullable disable

namespace Net21Labb3API.Migrations
{
    [DbContext(typeof(ApiContext))]
    [Migration("20221218014716_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Net21_Labb3_API.Models.Interest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Interests");
                });

            modelBuilder.Entity("Net21_Labb3_API.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("People");
                });

            modelBuilder.Entity("Net21_Labb3_API.Models.Website", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripton")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InterestId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InterestId");

                    b.ToTable("Websites");
                });

            modelBuilder.Entity("Net21_Labb3_API.Models.Interest", b =>
                {
                    b.HasOne("Net21_Labb3_API.Models.Person", null)
                        .WithMany("interests")
                        .HasForeignKey("PersonId");
                });

            modelBuilder.Entity("Net21_Labb3_API.Models.Website", b =>
                {
                    b.HasOne("Net21_Labb3_API.Models.Interest", null)
                        .WithMany("websites")
                        .HasForeignKey("InterestId");
                });

            modelBuilder.Entity("Net21_Labb3_API.Models.Interest", b =>
                {
                    b.Navigation("websites");
                });

            modelBuilder.Entity("Net21_Labb3_API.Models.Person", b =>
                {
                    b.Navigation("interests");
                });
#pragma warning restore 612, 618
        }
    }
}
